// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type RegisterDto = {
    /**
     * Full name of the user
     */
    name: string;
    /**
     * Username for login
     */
    username: string;
    /**
     * Email address
     */
    email: string;
    /**
     * Phone number
     */
    phone?: string;
    /**
     * Password for login
     */
    password: string;
};

export type LoginDto = {
    /**
     * Email or username
     */
    identifier: string;
    /**
     * Password
     */
    password: string;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterResponses = {
    201: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    201: unknown;
};

export type AuthControllerProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerProfileResponses = {
    200: unknown;
};
