// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { appControllerGetHello, authControllerLogin, authControllerProfile, authControllerRegister, type Options } from '../sdk.gen';
import type { AppControllerGetHelloData, AuthControllerLoginData, AuthControllerProfileData, AuthControllerRegisterData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const appControllerGetHelloQueryKey = (options?: Options<AppControllerGetHelloData>) => createQueryKey('appControllerGetHello', options);

export const appControllerGetHelloOptions = (options?: Options<AppControllerGetHelloData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await appControllerGetHello({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: appControllerGetHelloQueryKey(options)
    });
};

export const authControllerRegisterMutation = (options?: Partial<Options<AuthControllerRegisterData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerRegisterData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const authControllerLoginMutation = (options?: Partial<Options<AuthControllerLoginData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerLoginData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const authControllerProfileQueryKey = (options?: Options<AuthControllerProfileData>) => createQueryKey('authControllerProfile', options);

export const authControllerProfileOptions = (options?: Options<AuthControllerProfileData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await authControllerProfile({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: authControllerProfileQueryKey(options)
    });
};
